services:
  haven:
    container_name: haven
    image: haven
    build: .
    env_file: .env
    ports:
      - 3355:3355
    volumes:
      - ./blossom:/haven/blossom
      - ./db:/haven/db
      - ./relays_blastr.json:/haven/relays_blastr.json
      - ./relays_import.json:/haven/relays_import.json
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          # https://docs.docker.com/reference/compose-file/deploy/#memory
          memory: 2GB
