services:
  haven:
    container_name: haven
    image: sudocarlos/haven:v1.0.6
    build: .
    env_file: .env
    ports:
      - 3355:3355
    volumes:
      - ./data/blossom:/haven/data/blossom
      - ./data/db:/haven/db
      - ./relays_blastr.json:/haven/relays_blastr.json
      - ./relays_import.json:/haven/relays_import.json
      - ./data/tor:/var/lib/tor
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          # https://docs.docker.com/reference/compose-file/deploy/#memory
          memory: 2GB
